const menu =[
    {
        id:1,
        title:'main',
        listItems:[
            {
                id:1,
                title:"Homepage",
                url:'/',
                icon:"home.svg"
            },
            {
                id:2,
                title:"Profile",
                url:'/users/1',
                icon:"user.svg"
            }
        ]
    },
    {
        id:2,
        title:'lists',
        listItems:[
            {
                id:1,
                title:"Users",
                url:'/users',
                icon:"user.svg"
            },
            {
                id:2,
                title:"Products",
                url:'/products',
                icon:"products.svg"
            },
            {
                id:3,
                title:"Orders",
                url:'/orders',
                icon:"orders.svg"
            },
            {
                id:4,
                title:"Posts",
                url:'/posts',
                icon:"post2.svg"
            },
        ]
    },
    {
        id:3,
        title:'general',
        listItems:[
            {
                id:1,
                title:"Elements",
                url:'/',
                icon:"element.svg"
            },
            {
                id:2,
                title:"Notes",
                url:'/',
                icon:"notes.svg"
            },
            {
                id:3,
                title:"Forms",
                url:'/',
                icon:"forms.svg"
            },
            {
                id:4,
                title:"Calender",
                url:'/',
                icon:"calender.svg"
            },
        ]
    },
    {
        id:4,
        title:'Maintenance',
        listItems:[
            {
                id:1,
                title:"Settings",
                url:'/',
                icon:"setting.svg"
            },
            {
                id:2,
                title:"Backups",
                url:'/',
                icon:"backup.svg"
            },
        
        ]
    },
    {
        id:5,
        title:'analytics',
        listItems:[
            {
                id:1,
                title:"Charts",
                url:'/',
                icon:"chart.svg"
            },
            {
                id:2,
                title:"Logs",
                url:'/',
                icon:"log.svg"
            }
        ]
    },
]

export {menu};