const menu =[
    {
        id:1,
        title:'main',
        listItems:[
            {
                id:1,
                title:"Homepage",
                url:'/',
                icon:"home.svg"
            },
            {
                id:2,
                title:"Profile",
                url:'/users/1',
                icon:"user.svg"
            }
        ]
    },
    {
        id:2,
        title:'lists',
        listItems:[
            {
                id:1,
                title:"Users",
                url:'/users',
                icon:"user.svg"
            },
            {
                id:2,
                title:"Products",
                url:'/products',
                icon:"products.svg"
            },
            {
                id:3,
                title:"Orders",
                url:'/orders',
                icon:"orders.svg"
            },
            {
                id:4,
                title:"Posts",
                url:'/posts',
                icon:"post2.svg"
            },
        ]
    },
    {
        id:3,
        title:'general',
        listItems:[
            {
                id:1,
                title:"Elements",
                url:'/',
                icon:"element.svg"
            },
            {
                id:2,
                title:"Notes",
                url:'/',
                icon:"notes.svg"
            },
            {
                id:3,
                title:"Forms",
                url:'/',
                icon:"forms.svg"
            },
            {
                id:4,
                title:"Calender",
                url:'/',
                icon:"calender.svg"
            },
        ]
    },
    {
        id:4,
        title:'Maintenance',
        listItems:[
            {
                id:1,
                title:"Settings",
                url:'/',
                icon:"setting.svg"
            },
            {
                id:2,
                title:"Backups",
                url:'/',
                icon:"backup.svg"
            },
        
        ]
    },
    {
        id:5,
        title:'analytics',
        listItems:[
            {
                id:1,
                title:"Charts",
                url:'/',
                icon:"chart.svg"
            },
            {
                id:2,
                title:"Logs",
                url:'/',
                icon:"log.svg"
            }
        ]
    },
];

const topDealUsers =[
    {
        id:1,
        img:"",
        username:"Elva McDonald",
        email:"elva@gmail.com",
        amount:"3.668"
    },
    {
        id:2,
        img:"",
        username:"Linnie Nelson",
        email:"linnie@gmail.com",
        amount:"3.668"
    },
    {
        id:3,
        img:"",
        username:"Brent Reeves",
        email:"brent@gmail.com",
        amount:"2.998"
    },
    {
        id:4,
        img:"",
        username:"Adeline Watson",
        email:"adeline@gmail.com",
        amount:"2.512"
    },
    {
        id:5,
        img:"",
        username:"Elva McDonald",
        email:"elva@gmail.com",
        amount:"2.134"
    },
    {
        id:6,
        img:"",
        username:"Augusta McGee",
        email:"augusta@gmail.com",
        amount:"1.932"
    },
    {
        id:7,
        img:"",
        username:"Angel Thonas",
        email:"angel@gmail.com",
        amount:"1.568"
    },
]



export {menu,topDealUsers};